#!/bin/bash

set -x
ROOT=$(echo /apache-zookeeper-*)

ZOO_USER=${ZOO_USER:-"zookeeper"}
ZOO_LOG_LEVEL=${ZOO_LOG_LEVEL:-"INFO"}
ZOO_DATA_DIR=${ZOO_DATA_DIR:-"/data"}
ZOO_DATA_LOG_DIR=${ZOO_DATA_LOG_DIR:-"/data/log"}
ZOO_CONF_DIR=${ZOO_CONF_DIR:-"/conf"}
ZOO_CLIENT_PORT=${ZOO_CLIENT_PORT:-2181}
ZOO_SERVER_PORT=${ZOO_SERVER_PORT:-2888}
ZOO_ELECTION_PORT=${ZOO_ELECTION_PORT:-3888}
ZOO_TICK_TIME=${ZOO_TICK_TIME:-2000}
ZOO_INIT_LIMIT=${ZOO_INIT_LIMIT:-10}
ZOO_SYNC_LIMIT=${ZOO_SYNC_LIMIT:-5}
ZOO_HEAP_SIZE=${ZOO_HEAP_SIZE:-2G}
ZOO_MAX_CLIENT_CNXNS=${ZOO_MAX_CLIENT_CNXNS:-60}
ZOO_MIN_SESSION_TIMEOUT=${ZOO_MIN_SESSION_TIMEOUT:- $((ZOO_TICK_TIME*2))}
ZOO_MAX_SESSION_TIMEOUT=${ZOO_MAX_SESSION_TIMEOUT:- $((ZOO_TICK_TIME*20))}
ZOO_AUTOPURGE_SNAPRETAINCOUNT=${ZOO_AUTOPURGE_SNAPRETAINCOUNT:-3}
ZOO_AUTOPURGE_PURGEINTERVAL=${ZOO_AUTOPURGE_PURGEINTERVAL:-0}
ZOO_SNAPCOUNT=${ZOO_SNAPCOUNT:-50000}
ZOO_JUTE_MAXBUFFER=${ZOO_JUTE_MAXBUFFER:-0x9FFFFF}
ID_FILE="$ZOO_DATA_DIR/myid"
ZOO_CONFIG_FILE="$ZOO_CONF_DIR/zoo.cfg"
LOG4J_PROPERTIES="$ZOO_CONF_DIR/log4j.properties"
HOST=$(hostname)
DOMAIN=`hostname -d`
JVMFLAGS="-Xmx$ZOO_HEAP_SIZE -Xms$ZOO_HEAP_SIZE -Djute.maxbuffer=$ZOO_JUTE_MAXBUFFER"

APPJAR=$(echo $ROOT/*jar)
CLASSPATH="${ROOT}/lib/*:${APPJAR}:${ZOO_CONF_DIR}:"

if [[ $HOST =~ (.*)-([0-9]+)$ ]]; then
    NAME=${BASH_REMATCH[1]}
    ORD=${BASH_REMATCH[2]}
    MY_ID=$((ORD+1))
else
    echo "Failed to extract ordinal from hostname $HOST"
    exit 1
fi

mkdir -p $ZOO_DATA_DIR
mkdir -p $ZOO_DATA_LOG_DIR
echo $MY_ID >> $ID_FILE

echo "clientPort=$ZOO_CLIENT_PORT" >> $ZOO_CONFIG_FILE
echo "dataDir=$ZOO_DATA_DIR" >> $ZOO_CONFIG_FILE
echo "dataLogDir=$ZOO_DATA_LOG_DIR" >> $ZOO_CONFIG_FILE
echo "tickTime=$ZOO_TICK_TIME" >> $ZOO_CONFIG_FILE
echo "initLimit=$ZOO_INIT_LIMIT" >> $ZOO_CONFIG_FILE
echo "syncLimit=$ZOO_SYNC_LIMIT" >> $ZOO_CONFIG_FILE
echo "maxClientCnxns=$ZOO_MAX_CLIENT_CNXNS" >> $ZOO_CONFIG_FILE
echo "minSessionTimeout=$ZOO_MIN_SESSION_TIMEOUT" >> $ZOO_CONFIG_FILE
echo "maxSessionTimeout=$ZOO_MAX_SESSION_TIMEOUT" >> $ZOO_CONFIG_FILE
echo "autopurge.snapRetainCount=$ZOO_AUTOPURGE_SNAPRETAINCOUNT" >> $ZOO_CONFIG_FILE
echo "autopurge.purgeInterval=$ZOO_AUTOPURGE_PURGEINTERVAL" >> $ZOO_CONFIG_FILE
echo "snapCount=$ZOO_SNAPCOUNT" >> $ZOO_CONFIG_FILE
echo "jute.maxbuffer=$ZOO_JUTE_MAXBUFFER" >> $ZOO_CONFIG_FILE
echo "4lw.commands.whitelist=*" >> $ZOO_CONFIG_FILE
echo "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider" >> $ZOO_CONFIG_FILE

for (( i=1; i<=$ZOO_REPLICAS; i++ ))
do
    if [ $MY_ID -eq $i ]; then
		echo "server.$i=0.0.0.0:$ZOO_SERVER_PORT:$ZOO_ELECTION_PORT" >> $ZOO_CONFIG_FILE
    else
    	echo "server.$i=$NAME-$((i-1)).$DOMAIN:$ZOO_SERVER_PORT:$ZOO_ELECTION_PORT" >> $ZOO_CONFIG_FILE
    fi

done

rm -f $LOG4J_PROPERTIES

echo "zookeeper.root.logger=$ZOO_LOG_LEVEL, CONSOLE" >> $LOG4J_PROPERTIES
echo "zookeeper.console.threshold=$ZOO_LOG_LEVEL" >> $LOG4J_PROPERTIES
echo "zookeeper.log.threshold=$ZOO_LOG_LEVEL" >> $LOG4J_PROPERTIES
echo "zookeeper.log.dir=$ZOO_DATA_LOG_DIR" >> $LOG4J_PROPERTIES
echo "zookeeper.log.file=zookeeper.log" >> $LOG4J_PROPERTIES
echo "zookeeper.log.maxfilesize=256MB" >> $LOG4J_PROPERTIES
echo "zookeeper.log.maxbackupindex=10" >> $LOG4J_PROPERTIES
echo "zookeeper.tracelog.dir=$ZOO_DATA_LOG_DIR" >> $LOG4J_PROPERTIES
echo "zookeeper.tracelog.file=zookeeper_trace.log" >> $LOG4J_PROPERTIES
echo "log4j.rootLogger=\${zookeeper.root.logger}" >> $LOG4J_PROPERTIES
echo "log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender" >> $LOG4J_PROPERTIES
echo "log4j.appender.CONSOLE.Threshold=\${zookeeper.console.threshold}" >> $LOG4J_PROPERTIES
echo "log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout" >> $LOG4J_PROPERTIES
echo "log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n" >> $LOG4J_PROPERTIES

if [ -n "$JMXDISABLE" ]
then
    MAIN=org.apache.zookeeper.server.quorum.QuorumPeerMain
else
    MAIN="-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=$JMXPORT -Dcom.sun.management.jmxremote.authenticate=$JMXAUTH -Dcom.sun.management.jmxremote.ssl=$JMXSSL -Dzookeeper.jmx.log4j.disable=$JMXLOG4J org.apache.zookeeper.server.quorum.QuorumPeerMain"
fi

set -x
exec java -cp "$CLASSPATH" $JVMFLAGS $MAIN $ZOO_CONFIG_FILE
